baseURL = 'https://carrefour-de-la-liberte.fr'
languageCode = 'fr-fr'
title = 'Carrefour de la Liberté'
subtitle = 'Collectif Citoyen'
theme = 'ananke'

[[params.ananke_socials]]
name = "contact"
url = "mailto: contact@carrefour-de-la-liberte.fr"

